// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATcFPBEGDplHyGFirgh8RApb7RGZPZx14',
    appId: '1:346615412061:android:25fee47c63956dd61c64b4',
    messagingSenderId: '346615412061',
    projectId: 'spendee-d4216',
    databaseURL: 'https://spendee-d4216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendee-d4216.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANnuobAQdQz0J2Ocrw9gCU6d0882b2ngo',
    appId: '1:346615412061:ios:b8c066420d1f8e8a1c64b4',
    messagingSenderId: '346615412061',
    projectId: 'spendee-d4216',
    databaseURL: 'https://spendee-d4216-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'spendee-d4216.appspot.com',
    iosClientId: '346615412061-nju70geoc3s1ruav03uha6nchbrn8q11.apps.googleusercontent.com',
    iosBundleId: 'com.example.spendee',
  );
}
